# Generated by Django 5.2.1 on 2025-06-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winas', '0002_alter_employeeperformance_actual_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresultarea',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kras', to='winas.pillar'),
        ),
        migrations.AlterField(
            model_name='performancetarget',
            name='kra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_targets', to='winas.keyresultarea'),
        ),
    ]
