# Generated by Django 5.2.3 on 2025-10-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winas', '0004_alter_keyresultarea_pillar_and_more'),
    ]

    operations = [
    ]
