# Generated by Django 5.2.3 on 2025-10-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winas', '0005_auto_20251014_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeperformance',
            unique_together={('user', 'kra', 'period_under_review')},
        ),
        migrations.RemoveField(
            model_name='performancetarget',
            name='kra',
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='kra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_performances', to='winas.keyresultarea'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='performance_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='winas.performancetarget'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='pillar_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Employee's annual salary for bonus calculation.", max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pillar',
            unique_together={('performance_target', 'pillar_name')},
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='performance_target',
        ),
    ]
