# Generated by Django 5.2.3 on 2025-10-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winas', '0006_alter_employeeperformance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the KPI and how it's measured.", null=True)),
                ('target_value', models.IntegerField(blank=True, help_text='The numerical target figure for this specific KPI.', null=True)),
                ('annual_target', models.IntegerField(blank=True, help_text='The annual target for this KPI.', null=True)),
                ('weight', models.IntegerField(help_text='The weight assigned to this KPI within its KRA.')),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='winas.keyresultarea')),
            ],
            options={
                'verbose_name': 'Key Performance Indicator',
                'verbose_name_plural': 'Key Performance Indicators',
                'unique_together': {('kra', 'kpi_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='employeeperformance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='softskillrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_performances', to='winas.kpi'),
        ),
        migrations.AddField(
            model_name='softskillrating',
            name='soft_skill_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soft_skill_ratings', to='winas.kpi'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeperformance',
            unique_together={('user', 'kpi', 'period_under_review')},
        ),
        migrations.AlterUniqueTogether(
            name='softskillrating',
            unique_together={('user', 'soft_skill_kpi', 'period_under_review')},
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='kra',
        ),
        migrations.RemoveField(
            model_name='softskillrating',
            name='soft_skill_kra',
        ),
    ]
