# Generated by Django 5.2.3 on 2025-10-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winas', '0007_kpi_alter_employeeperformance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the metrics category.', null=True)),
                ('weight', models.IntegerField(blank=True, help_text='The weight assigned to this metrics category.', null=True)),
            ],
            options={
                'verbose_name': 'Metrics',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pillar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pillar',
            name='metrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='winas.metrics'),
        ),
        migrations.AlterUniqueTogether(
            name='pillar',
            unique_together={('metrics', 'pillar_name')},
        ),
    ]
