# Generated by Django 5.2.3 on 2025-11-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winas', '0008_metrics_alter_pillar_unique_together_pillar_metrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeperformance',
            name='performance_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_performances', to='winas.performancetarget'),
        ),
        migrations.AddField(
            model_name='performancetarget',
            name='kra',
            field=models.ForeignKey(blank=True, help_text='The Key Result Area this performance target belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to='winas.keyresultarea'),
        ),
        migrations.AddField(
            model_name='softskillrating',
            name='soft_skill_kra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soft_skill_ratings', to='winas.keyresultarea'),
        ),
    ]
