# Generated by Django 5.2.3 on 2025-11-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winas', '0009_add_kra_to_performance_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancetarget',
            name='annual_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The annual target, which might differ from the primary target_value.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='performancetarget',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The numerical target figure (e.g., 40.5, 80000000.00, 98.75).', max_digits=15, null=True),
        ),
    ]
