# Generated by Django 5.2.3 on 2025-12-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winas', '0010_change_target_fields_to_decimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='weight',
        ),
    ]
